### ISSUE TITLE
Migrate to pkexec

### ISSUE THREAD

**Issue by ghost** [rapgenic/cinnamon-remove-application#1]
Greetings, I was checking that because of the new version of Linux Mint they will be releasing, the people of Linux Mint make some new changes, one of them was the deprecation of gksu in order to favor pkexec (you can check the [commit here](https://github.com/linuxmint/mint-common/commit/96deca168cc267560f19696d6d14896ad6b9a0a8)).

It make take some time but if possible try to migrate to pkexec as well since many of the programs will not be able to run on gksu (which also helps because Archlinux deprecated gksu a long time ago and you can barely see apps with them, except the pending to migrate or rewrite)

**Comment by rapgenic** [comment]
Hi, sorry for answering late. I've just migrated to pkexec and it should be working now.
I'm updating the AUR package in a few moments.
